'$schema' = "https://starship.rs/config-schema.json"

format = """
[î‚¶](#1500ff)\
$username\
[î‚°](fg:#1500ff bg:#DA627D )\
$directory\
[î‚°](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[î‚°](fg:#FCA17D bg:#86BBD8)\
$c\
$golang\
$nodejs\
$rust\
[î‚°](fg:#86BBD8 bg:#2ec122)\
$docker_context\
$conda\
$python\
[î‚° ](fg:#2ec122)\
$fill\
$jobs\
[ î‚¶](fg:#bc57eb)\
$time\
$battery\
[î‚´ ](fg:#bc57eb)\
$line_break\
[â‹™  ](fg:#0094ff)\
"""

# Disable the blank line at the start of the prompt
add_newline = true

# A continuation prompt that displays two filled in arrows
continuation_prompt = '[~~> ](fg:#d950ff)'

right_format = """
[î‚¶](fg:#bc57eb)\
$cmd_duration\
$status\
[î‚´](fg:#bc57eb)\
"""

[line_break]
disabled = false

[character]
disabled = false
error_symbol = "[ âŒ ](fg:#ff0000)"
success_symbol = "[ âœ… ](fg:#00ff2d)"

[fill]
disabled = false
symbol = "-"

[battery]
disabled = false
full_symbol = " ğŸ”‹ "
charging_symbol = " âš¡ï¸ "
discharging_symbol = " â‡£ "

[[battery.display]] # 'bold red' style and discharging_symbol when capacity is between 0% and 10%
threshold = 10
style = 'blink red'
discharging_symbol = ' ğŸ’€ '

[[battery.display]]
threshold = 30
style = 'bold yellow' # when capacity is over 30%, the battery indicator will not be displayed

[[battery.display]]
threshold = 99
style = 'bold green'

[time]
disabled = false
time_format = "%R"           # Hour:Minute Format
style = 'bold fg:#000000 bg:#bc57eb'
format = '[$time ïº ]($style)'

[cmd_duration]
style = 'fg:bold #000000 bg:#bc57eb'
format = "[ ï‰” $duration ]($style)"
show_milliseconds = true
min_time = 500
show_notifications = true
min_time_to_notify = 300_000
notification_timeout = 5_000

[status]
disabled = false
style = "fg:bold #000000 bg:#bc57eb"
map_symbol = true
recognize_signal_code = true
pipestatus = true
symbol = 'ğŸ”´ '
signal_symbol = "âš¡ "
success_symbol = 'ğŸŸ¢ SUCCESS'
sigint_symbol = "â›” "
not_executable_symbol = "ğŸš« "
not_found_symbol = "ğŸ” "
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style)'

[jobs]
symbol_threshold = 1
number_threshold = 1
format = "[ $symbol$number jobs ]($style)"

[username]
show_always = true
style_user = "fg:#FFFFFF bg:#1500ff"
style_root = "fg:#FFFFFF bg:#ff0000"
format = '[$user ]($style)'
disabled = false

[directory]
style = "fg:bold #000000 bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

# Git status:
[git_branch]
symbol = "ï˜"
style = "fg:bold #000000 bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:bold #000000 bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

# Languages:
[c]
symbol = "î˜"
style = "fg:bold #000000 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = "ğŸ¹"
style = "fg:bold #000000 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "fg:bold #000000 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨"
style = "fg:bold #000000 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

# Environment/Context:
[conda]
style = "fg:bold #000000 bg:#2ec122"
symbol = "ğŸ…’ "
ignore_base = false
format = '[$symbol$environment]($style)'

[docker_context]
symbol = " ïŒˆ "
style = "fg:bold #000000 bg:#2ec122"
format = '[ $symbol $context ]($style)'

[python]
version_format = "v${raw}"
style = "fg:bold #000000 bg:#2ec122"
symbol = "î˜†"
format = '[ [$symbol](fg:#bc57eb bg:#2ec122) ($version)]($style)'
